# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "backend"
    schedule:
      interval: "weekly"
