version: "3.9"

services:
  piplayer.frontend:
    container_name: frontend
    image: piplayer.${FRONTEND_IMAGE}:latest
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

  piplayer.backend:
    environment:
      - CORS_ORIGINS
      - MEDIA
    container_name: backend
    image: piplayer.backend:latest
    restart: always
    volumes:
      - "${MEDIA}:${MEDIA}:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

  piplayer.proxy:
    container_name: proxy
    image: piplayer.proxy:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - "${MEDIA}:/usr/share/nginx/html:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

networks:
  piplayer-network:
    driver: bridge
