# Docker composition file. Use `docker-compose up -d` to start the services.

# Warning: If this file is placed in a subdirectory, the volume mappings break.

version: "3.9"

services:
  piplayer.frontend:
    container_name: frontend
    image: piplayer.frontend:latest
    restart: always
    ports:
      - "3000:80"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

  piplayer.backend:
    container_name: backend
    image: piplayer.backend:latest
    restart: always
    volumes:
       - "${MEDIA:-/var/www/html/media}:/var/www/html/media:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
  
  piplayer.proxy:
    container_name: proxy
    image: piplayer.proxy:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - "${MEDIA:-/var/www/html/media}:/usr/share/nginx/html:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL


networks:
  piplayer-network:
    driver: bridge
