version: "3.9"

services:
  piplayer.frontend:
    container_name: frontend
    image: ${FRONTEND_IMAGE}
    restart: always
    ports:
      - ${FRONTEND_PORT}:80
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL

  piplayer.backend:
    environment:
      - CORS_ORIGINS
    container_name: backend
    image: piplayer.backend:latest
    restart: always
    volumes:
       - "${MEDIA}:/var/www/html/media:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
  
  piplayer.proxy:
    container_name: proxy
    image: piplayer.proxy:latest
    restart: always
    ports:
      - 8080:80
    volumes:
      - "${MEDIA}:/usr/share/nginx/html:ro"
    networks:
      - piplayer-network
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL


networks:
  piplayer-network:
    driver: bridge
