#!/bin/bash
set -euxo pipefail

# To use this script as a hook for continuous deployment, create a
# symlink by running the following command from the repository root:
# ln -snvf $(pwd)/post-receive .git/hooks/post-receive

WORKDIR=~/piplayer

# From https://gist.github.com/deanrather/3697539
echo "Determining branch"
if ! [ -t 0 ]
then
  read -a ref
fi

if [[ "${ref[2]}" == "refs/heads/deploy/production" ]] && [[ "$(hostname)" == "bier" ]]
then
  GIT_WORK_TREE="$WORKDIR" git checkout -f deploy/production
  pushd "$WORKDIR"
  ! [[ "$(sudo docker ps | grep piplayer)" ]] || sudo docker-compose --env-file production.env down
  sudo bash ./run.sh production.env
fi
