name: Frontend

on: [push]

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  frontend:
    name: Frontend test, lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        run: cd frontend && npm install

      - name: Copy env file
        run: "cp .env.development frontend/.env.test"

      - name: Run tests
        run: |
          cd frontend
          npx vitest --run

      - name: Lint and format
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          eslint_dir: frontend/
          eslint_extensions: js,jsx,ts,tsx
          prettier: true
          prettier_dir: frontend/
