name: Frontend

on: [push, pull_request]

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  test-lint-and-format:
    name: Test lint and format
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js dependencies
        run: cd frontend && npm ci

      - name: Run tests
        run: npx vitest --run

      - name: Lint and format
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          eslint_dir: frontend/
          eslint_extensions: js,jsx,ts,tsx
          prettier: true
          prettier_dir: frontend/
