name: Lint

on: [push, pull_request]

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: cd frontend && npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2.3.0
        with:
          eslint: true
          eslint_dir: frontend/
          eslint_extensions: js,jsx,ts,tsx
          prettier: true
          prettier_dir: frontend/
